matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
      output: wordlist.dic
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          attributes: []
          ignores:
            - code
            - pre
    sources:
      - "**/*.md"
    default_encoding: utf-8
